library(shiny)
library(shinydashboard)
library(rhandsontable)
library(data.table)
library(shinydashboardPlus)
library(sendmailR)
library(shinyalert)

source('./ui_controls.R')
source('./server_group.R')
source('./Functions/calcTable2.R')
source('./Functions/fill8Final.R')
source('./Functions/fill4Final.R')
source('./Functions/fill1Final.R')
source('./Functions/getGroupPositions.R')
source('./Functions/check_answers.R')
